name: Scheduled Task

on:
  schedule:
    # 5분마다 실행 (매 5분마다 실행)
    - cron: '*/5 * * * *'
  workflow_dispatch: # 수동 실행도 가능하도록 설정

jobs:
  echo-time:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Echo current time
      run: |
        echo "Current time: $(date)"
        echo "GitHub Actions run at: $(date '+%Y-%m-%d %H:%M:%S %Z')"
        echo "Local timezone: $(date +%Z)"
        echo "UTC time: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        echo "KST time: $(TZ=Asia/Seoul date '+%Y-%m-%d %H:%M:%S KST')"
        echo "Workflow run ID: ${{ github.run_id }}"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
        
    - name: Show environment info
      run: |
        echo "Runner OS: $(uname -s)"
        echo "Runner Architecture: $(uname -m)"
        echo "Working Directory: $(pwd)" 